// <auto-generated />
namespace Draftkings.Ownership.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class klo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(klo));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070106369_klo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
